CREATE TABLE exchange_record (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 4) NOT NULL,
    SOURCE_CURRENCY VARCHAR(10) NOT NULL,
    TARGET_CURRENCY VARCHAR(10) NOT NULL,
    EXCHANGE_RATE DECIMAL(19, 4) NOT NULL,
    CONVERTED_AMOUNT DECIMAL(19, 4) NOT NULL
);

